# Generated by Django 4.0.4 on 2022-05-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=57)),
                ('local', models.CharField(max_length=20)),
                ('cursoFrequentado', models.CharField(max_length=31)),
                ('periodoNaInstituicao', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Linguagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=31)),
                ('linkDaPessoaLusofona', models.URLField(default='')),
                ('linkDaPessoaLinkedIn', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.TextField()),
                ('linguagemUtilizada', models.ManyToManyField(to='portfolio.linguagen')),
            ],
        ),
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('ano', models.IntegerField()),
                ('descricao', models.TextField()),
                ('docente_praticas', models.ManyToManyField(related_name='caderias', to='portfolio.pessoa')),
                ('docente_teorica', models.ManyToManyField(to='portfolio.pessoa')),
                ('linguagens', models.ManyToManyField(to='portfolio.linguagen')),
                ('projetos', models.ManyToManyField(to='portfolio.projeto')),
            ],
        ),
    ]
