# Generated by Django 4.0.4 on 2022-05-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='semestre',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=1),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='nome',
            field=models.CharField(max_length=57),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
