# Generated by Django 4.0.4 on 2022-05-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_cadeira_semestre_alter_cadeira_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='anoLetivoFrequentado',
            field=models.IntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='ano',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
        ),
    ]
