# Generated by Django 4.0.4 on 2022-05-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_cadeira_anoletivofrequentado_alter_cadeira_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='anoLetivoFrequentado',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='linkDaPessoaLinkedIn',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='linkDaPessoaLusofona',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome',
            field=models.CharField(max_length=31),
        ),
    ]
