# Generated by Django 4.0.4 on 2022-05-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_cadeira_anoletivofrequentado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
