# Generated by Django 4.0.4 on 2022-05-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_cadeira_ects'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='urlCadeira',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
