# Generated by Django 4.0.4 on 2022-05-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_cadeira_urlcadeira'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='anoLetivoEmQueFoiRealizado',
            field=models.CharField(default='2020/21', max_length=15),
        ),
        migrations.AddField(
            model_name='projeto',
            name='linkGitHub',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='linkVideoYoutube',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='participantes',
            field=models.ManyToManyField(to='portfolio.pessoa'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(max_length=500),
        ),
    ]
