# Generated by Django 4.0.4 on 2022-05-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_projeto_anoletivoemquefoirealizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='anoLetivoEmQueFoiRealizado',
            field=models.CharField(blank=True, default='2020/21', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='participantes',
            field=models.ManyToManyField(blank=True, null=True, to='portfolio.pessoa'),
        ),
    ]
