# Generated by Django 4.0.4 on 2022-05-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_projeto_anoletivoemquefoirealizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='linkPortfolioPW',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
