# Generated by Django 4.0.4 on 2022-05-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_pessoa_linkportfoliopw'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(default='', upload_to=None),
        ),
    ]
