# Generated by Django 4.0.4 on 2022-05-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_projeto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='imagem',
            field=models.ImageField(default='', upload_to=None),
        ),
    ]
