# Generated by Django 4.0.4 on 2022-05-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_escola_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='imagem',
            field=models.ImageField(default='', upload_to='portfolio/images'),
        ),
    ]
