# Generated by Django 4.0.4 on 2022-05-27 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_alter_escola_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='imagem',
        ),
    ]
