# Generated by Django 4.0.4 on 2022-05-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_remove_escola_imagem_remove_projeto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='projetos',
            field=models.ManyToManyField(blank=True, null=True, to='portfolio.projeto'),
        ),
    ]
