# Generated by Django 4.0.4 on 2022-05-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_alter_cadeira_docente_praticas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='docente_praticas',
            field=models.ManyToManyField(related_name='praticas', to='portfolio.pessoa'),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='docente_teorica',
            field=models.ManyToManyField(related_name='teoricas', to='portfolio.pessoa'),
        ),
    ]
