# Generated by Django 4.0.4 on 2022-05-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_alter_cadeira_docente_praticas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='linguagens',
            field=models.ManyToManyField(related_name='linguagem', to='portfolio.linguagen'),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='projetos',
            field=models.ManyToManyField(blank=True, null=True, related_name='projeto', to='portfolio.projeto'),
        ),
    ]
