# Generated by Django 4.0.4 on 2022-05-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_alter_cadeira_linguagens_alter_cadeira_projetos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='linguagemUtilizada',
            field=models.ManyToManyField(related_name='linguagemUsada', to='portfolio.linguagen'),
        ),
    ]
