# Generated by Django 4.0.4 on 2022-05-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_alter_projeto_linguagemutilizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='linguagens',
            field=models.ManyToManyField(related_name='linguagemLecionada', to='portfolio.linguagen'),
        ),
    ]
