# Generated by Django 4.0.4 on 2022-05-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_alter_cadeira_linguagens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='linguagens',
            field=models.ManyToManyField(related_name='linguagem', to='portfolio.linguagen'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='linguagemUtilizada',
            field=models.ManyToManyField(to='portfolio.linguagen'),
        ),
    ]
