# Generated by Django 4.0.4 on 2022-05-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_alter_projeto_linguagemutilizada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeExtenso', models.CharField(max_length=75)),
                ('sigla', models.CharField(max_length=10)),
                ('anoDeCriacao', models.IntegerField()),
                ('criador', models.CharField(max_length=115)),
                ('linkSiteOficial', models.URLField(blank=True, default='', null=True)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
