# Generated by Django 4.0.4 on 2022-05-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_laboratorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='titulo',
            field=models.CharField(max_length=75),
        ),
    ]
