# Generated by Django 4.0.4 on 2022-05-29 07:26

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontuacaoQuizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('pontuacao', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=portfolio.models.resolution_path),
        ),
    ]
